server:
  port: 8802

spring:
  application:
    name: qs-analysis-server
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.64.130:3306/qs
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.64.130
    port: 6379
  cache:
    cache-names: redis
  kafka:
    consumer:
      bootstrap-servers: 192.168.64.130:9092
      group-id: qs-analysis-group
      enable-auto-commit: false # 是否自动提交偏移量，默认是true。为了避免出现重复数据和数据丢失，设置为false，然后手动提交偏移量
      auto-offset-reset: earliest # 从头开始读取
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # 键的反序列化方式
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer # 值的反序列化方式
    listener:
      ack-mode: manual_immediate # 消息确认模式

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml